### ISSUE TITLE
EntityPointer -> Entity transition

### ISSUE THREAD

**Issue by renemilk** [dune-community/dune-xt-grid#3]
_From @renemilk on August 6, 2015 11:48_

EntityPointers are deprecated by means of copy-able entities in DUNE 2.4 onwards.

_Copied from original issue: wwu-numerik/dune-stuff#71_

**Comment by renemilk** [comment]
See also #77

**Comment by renemilk** [comment]
I think @tobiasleibner  recently worked on this. Any idea how much is left to do?

**Comment by tobiasleibner** [comment]
I think there shouldn't be much left to do. In the [compatible_with_core_2.5](https://github.com/dune-community/dune-xt-grid/tree/compatible_with_core_2.5) I replaced one remaining use of EntityPointers in dc8c97244cc5b3450f096dbdf31116b4a7df24de and all tests compile and pass with the 2.5 core modules without deprecation warnings. So if there are remaining uses ``EntityPointer``, they are in untested parts of the code.

**Comment by tobiasleibner** [comment]
I guess this can be closed now, as the current master works fine with the 2.5 core modules without any deprecation warnings or compilation errors. There may be some uses of ``EntityPointer`` remaining in untested parts of the code, but that would be solved with #11.
